### ISSUE TITLE
Typo in protocol=https?

### ISSUE THREAD

**Issue by ThyMYthOS** [stalwartlabs/website#14]
The documentation states that `https` is a valid protocol:
https://github.com/stalwartlabs/website/blame/0bc37a769dd140d2036b12e592fc5f1855899c9b/docs/server/listener.md#L34

But the examples below mention `http`.
https://github.com/stalwartlabs/website/blame/0bc37a769dd140d2036b12e592fc5f1855899c9b/docs/server/listener.md#L126

Which one is correct?

**Comment by mdecimus** [comment]
Thanks, this is going to be fixed today.

**Comment by ThyMYthOS** [comment]
Is `http` still valid? According to https://github.com/stalwartlabs/mail-server/blob/53f0222f308b3e844c158fc0e603d10361da3c63/crates/main/src/main.rs#L116 it seems that it's actually ignored.

**Comment by mdecimus** [comment]
Yes, the `http` listener type is only used by the SMTP-only binary. The All-in-one binary uses the `jmap` listener type.
