### ISSUE TITLE
postmaster inbox / auto-dmarc location?

### ISSUE THREAD

**Issue by unusualevent** [stalwartlabs/website#23]
I'm curious if it's possible for there to be an address just read by stalwart for the dmarc reports, that deletes the emails after it's gotten the report info / after a certain amount of time. Maybe with some disclaimer when it detects a non-dmarc email that the inbox isn't monitored (but that could lead to an infinite loop).

Right now those go to the catch-all email address.

**Comment by mdecimus** [comment]
Yes, you can take a look at the [report analysis](https://stalw.art/docs/smtp/authentication/analysis) section. It is possible to specify the e-mail addresses where Stalwart will check for incoming reports and if you set `forward` to `false` the reports will be deleted after analysis.
