### ISSUE TITLE
FoundationDB instructions on installation page

### ISSUE THREAD

**Issue by NetOpWibby** [stalwartlabs/website#3]
I went through the installation, chose FoundationDB as my backend, and was confused about why I was seeing Stalwart crash.

It wasn't until I installed FoundationDB that the issues stopped.

**Comment by NetOpWibby** [comment]
I'm unable to log into accounts now but that's a different issue.

**Comment by mdecimus** [comment]
If you are still having issues login into your accounts please open a discussion including your server logs and config file at the mail-server repository. Thanks.
