### ISSUE TITLE
Is there documentation on which projects are production-ready?

### ISSUE THREAD

**Issue by JonathanWilbur** [stalwartlabs/website#6]
I believe all of the servers are not version 1.0.0 or higher yet. Does this mean that they are not suitable for hosting real email yet? What does this lower version entail?

**Comment by mdecimus** [comment]
All servers are production ready currently, the reason why they are not version `1.0.0` yet is because their database layouts and/or configuration formats might change which will require data migration when upgrading. Version `1.0.0` is expected for early or mid 2024.

**Comment by JonathanWilbur** [comment]
Thank you! Closing.
