### ISSUE TITLE
Document password reset

### ISSUE THREAD

**Issue by stappersg** [stalwartlabs/website#9]
Hi,

In my notes I have
```
🔑 The administrator account is 'admin' with password 'Str1ngFr0mInst@ll3r'.
```

However:

```
$ stalwart-cli -u https://127.0.0.1:8080 -c Str1ngFr0mInst@ll3r report list
Failed to deserialize response: EOF while parsing a value at line 1 column 0
$ stalwart-cli -u https://127.0.0.1:8080 -c OTHERPASSWORD report list
Failed to deserialize response: EOF while parsing a value at line 1 column 0
$
```

How to reset the password?

FWIW: Pasting that knowledge here, makes it possible for others to add to website.

**Comment by stappersg** [comment]
Link to https://github.com/stalwartlabs/mail-server/issues/157

**Comment by mdecimus** [comment]
Hi,

You need to change from your LDAP or SQL directory as version 0.4.0 relies on external directories for authentication and does not include a user management tool. Version 0.5.0 will include an internal directory and the procedure to change and reset passwords will be documented.
